---

- hosts: all
  become: true
  vars_files:
     - vars.yaml
  strategy: free
  tasks:
  - name: Adding Kubernetes repository to the system including gpkg keys
    yum_repository:
      name: kubernetes
      description: Kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - name: setting SELinux to premissive mode
    selinux:
      policy: targeted
      state: permissive
  - name: Installing the required packages now
    yum: name={{ item }} state=present update_cache=yes
    with_items: "{{ PACKAGES }}"
  - name: Enable and Start Docker
    systemd: name=docker state=started enabled=yes
  - name: Enable Kubelet
    systemd: name=kubelet state=started enabled=yes
  - name: traffic route fix
    shell: |
        cat <<EOF >  /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF
        
        sysctl --system
  - name: collecting cgroup info of docker
    shell: docker info | grep -i cgroup
    register: docker_cgroup
  - name: collecting cgroup info of installed kubeadm
    shell: cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf | grep "cgroup-driver="
    register: kubeadm_cgroup
  - name: Configure cgroup driver used by kubelet
    shell: sed -i "s/cgroup-driver=systemd/cgroup-driver=cgroupfs/g" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    when: docker_cgroup.stdout != kubeadm_cgroup.stdout