# -*- mode: ruby -*-
# vi: set ft=ruby :


hosts = {
"node1" => "192.168.100.77.10",
"node2" => "192.168.100.77.11",
"node3" => "192.168.100.77.12",
"node4" => "192.168.100.77.13"
}

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
	config.ssh.forward_agent = true
	check_guest_additions = false
	functional_vboxsf = false
	
	config.vm.box = "bento/centos-7.4"
	hosts.each do |name, ip|
	     config.vm.define name do |machine|
		    machine.vm.network :private_network, ip: ip
			machine.vm.provider "virtualbox" do |v|
			       v.name = name
		    end
		end
	end
	
end
